export const INSTRUCTIONS = {
    0x00: "BRK",
    0x01: "ORA (Indirect,X)",
    0x02: "Undefined",
    0x03: "Undefined",
    0x04: "Undefined",
    0x05: "ORA Zero Page",
    0x06: "RMB0 Zero Page",
    0x07: "Undefined",
    0x08: "PHP",
    0x09: "ORA Immediate",
    0x0A: "ASL Accumulator",
    0x0B: "Undefined",
    0x0C: "Undefined",
    0x0D: "ORA Absolute",
    0x0E: "Undefined",
    0x0F: "Undefined",
    0x10: "BPL",
    0x11: "ORA (Indirect),Y",
    0x12: "Undefined",
    0x13: "Undefined",
    0x14: "Undefined",
    0x15: "ORA Zero Page,X",
    0x16: "RMB2 Zero Page,X",
    0x17: "Undefined",
    0x18: "CLC",
    0x19: "ORA Absolute,Y",
    0x1A: "Undefined",
    0x1B: "Undefined",
    0x1C: "Undefined",
    0x1D: "ORA Absolute,X",
    0x1E: "ASL Absolute,X",
    0x1F: "Undefined",
    0x20: "JSR Absolute",
    0x21: "AND (Indirect,X)",
    0x22: "Undefined",
    0x23: "Undefined",
    0x24: "BIT Zero Page",
    0x25: "AND Zero Page",
    0x26: "ROL Zero Page",
    0x27: "Undefined",
    0x28: "PLP",
    0x29: "AND Immediate",
    0x2A: "ROL Accumulator",
    0x2B: "Undefined",
    0x2C: "BIT Absolute",
    0x2D: "AND Absolute",
    0x2E: "ROL Absolute",
    0x2F: "Undefined",
    0x30: "BMI",
    0x31: "AND (Indirect),Y",
    0x32: "Undefined",
    0x33: "Undefined",
    0x34: "Undefined",
    0x35: "AND Zero Page,X",
    0x36: "ROL Zero Page,X",
    0x37: "Undefined",
    0x38: "SEC",
    0x39: "AND Absolute,Y",
    0x3A: "Undefined",
    0x3B: "Undefined",
    0x3C: "Undefined",
    0x3D: "AND Absolute,X",
    0x3E: "ROL Absolute,X",
    0x3F: "Undefined",
    0x40: "RTI",
    0x41: "EOR (Indirect,X)",
    0x42: "Undefined",
    0x43: "Undefined",
    0x44: "Undefined",
    0x45: "EOR Zero Page",
    0x46: "LSR Zero Page",
    0x47: "Undefined",
    0x48: "PHA",
    0x49: "EOR Immediate",
    0x4A: "LSR Accumulator",
    0x4B: "Undefined",
    0x4C: "JMP Absolute",
    0x4D: "EOR Absolute",
    0x4E: "LSR Absolute",
    0x4F: "Undefined",
    0x50: "BVC",
    0x51: "EOR (Indirect),Y",
    0x52: "Undefined",
    0x53: "Undefined",
    0x54: "Undefined",
    0x55: "EOR Zero Page,X",
    0x56: "LSR Zero Page,X",
    0x57: "Undefined",
    0x58: "CLI",
    0x59: "EOR Absolute,Y",
    0x5A: "Undefined",
    0x5B: "Undefined",
    0x5C: "Undefined",
    0x5D: "EOR Absolute,X",
    0x5E: "LSR Absolute,X",
    0x5F: "Undefined",
    0x60: "RTS",
    0x61: "ADC (Indirect,X)",
    0x62: "Undefined",
    0x63: "Undefined",
    0x64: "Undefined",
    0x65: "ADC Zero Page",
    0x66: "ROR Zero Page",
    0x67: "Undefined",
    0x68: "PLA",
    0x69: "ADC Immediate",
    0x6A: "ROR Accumulator",
    0x6B: "Undefined",
    0x6C: "JMP Indirect",
    0x6D: "ADC Absolute",
    0x6E: "ROR Absolute",
    0x6F: "Undefined",
    0x70: "BVS",
    0x71: "ADC (Indirect),Y",
    0x72: "Undefined",
    0x73: "Undefined",
    0x74: "Undefined",
    0x75: "ADC Zero Page,X",
    0x76: "ROR Zero Page,X",
    0x77: "Undefined",
    0x78: "SEI",
    0x79: "ADC Absolute,Y",
    0x7A: "Undefined",
    0x7B: "Undefined",
    0x7C: "Undefined",
    0x7D: "ADC Absolute,X",
    0x7E: "ROR Absolute,X",
    0x7F: "Undefined",
    0x80: "Undefined",
    0x81: "STA (Indirect),X",
    0x82: "Undefined",
    0x83: "Undefined",
    0x84: "STY Zero Page",
    0x85: "Undefined",
    0x86: "STX Zero Page",
    0x87: "Undefined",
    0x88: "DEY",
    0x89: "Undefined",
    0x8A: "TXA",
    0x8B: "Undefined",
    0x8C: "STY Absolute",
    0x8D: "STA Absolute",
    0x8E: "STX Absolute",
    0x8F: "Undefined",
    0x90: "BCC",
    0x91: "STA (Indirect),Y",
    0x92: "Undefined",
    0x93: "Undefined",
    0x94: "STY Zero Page,X",
    0x95: "STA Zero Page,X",
    0x96: "STX Zero Page,Y",
    0x97: "Undefined",
    0x98: "TYA",
    0x99: "STA Absolute,Y",
    0x9A: "TXS",
    0x9B: "Undefined",
    0x9C: "Undefined",
    0x9D: "STA Absolute,X",
    0x9E: "Undefined",
    0x9F: "Undefined",
    0xA0: "LDY Immediate",
    0xA1: "LDA (Indirect),X",
    0xA2: "LDX Immediate",
    0xA3: "Undefined",
    0xA4: "LDY Zero Page",
    0xA5: "LDA Zero Page",
    0xA6: "LDX Zero Page",
    0xA7: "Undefined",
    0xA8: "TAY",
    0xA9: "LDA Immediate",
    0xAA: "TAX",
    0xAB: "Undefined",
    0xAC: "LDY Absolute",
    0xAD: "LDA Absolute",
    0xAE: "LDX Absolute",
    0xAF: "Undefined",
    0xB0: "BCS",
    0xB1: "LDA (Indirect),Y",
    0xB2: "Undefined",
    0xB3: "Undefined",
    0xB4: "LDY Zero Page,X",
    0xB5: "LDA Zero Page,X",
    0xB6: "LDX Zero Page,Y",
    0xB7: "Undefined",
    0xB8: "CLV",
    0xB9: "LDA Absolute,Y",
    0xBA: "TSX",
    0xBB: "Undefined",
    0xBC: "LDY Absolute,X",
    0xBD: "LDA Absolute,X",
    0xBE: "LDX Absolute,Y",
    0xBF: "Undefined",
    0xC0: "CPY Immediate",
    0xC1: "CMP (Indirect,X)",
    0xC2: "Undefined",
    0xC3: "Undefined",
    0xC4: "CPY Zero Page",
    0xC5: "CMP Zero Page",
    0xC6: "DEC Zero Page",
    0xC7: "Undefined",
    0xC8: "INY",
    0xC9: "CMP Immediate",
    0xCA: "DEX",
    0xCB: "Undefined",
    0xCC: "CPY Absolute",
    0xCD: "CMP Absolute",
    0xCE: "DEC Absolute",
    0xCF: "Undefined",
    0xD0: "BNE",
    0xD1: "CMP (Indirect),Y",
    0xD2: "Undefined",
    0xD3: "Undefined",
    0xD4: "Undefined",
    0xD5: "CMP Zero Page,X",
    0xD6: "DEC Zero Page,X",
    0xD7: "Undefined",
    0xD8: "CLD",
    0xD9: "CMP Absolute,Y",
    0xDA: "Undefined",
    0xDB: "Undefined",
    0xDC: "Undefined",
    0xDD: "CMP Absolute,X",
    0xDE: "DEC Absolute,X",
    0xDF: "Undefined",
    0xE0: "CPX Immediate",
    0xE1: "SBC (Indirect,X)",
    0xE2: "Undefined",
    0xE3: "Undefined",
    0xE4: "CPX Zero Page",
    0xE5: "SBC Zero Page",
    0xE6: "INC Zero Page",
    0xE7: "Undefined",
    0xE8: "INX",
    0xE9: "SBC Immediate",
    0xEA: "NOP",
    0xEB: "Undefined",
    0xEC: "CPX Absolute",
    0xED: "SBC Absolute",
    0xEE: "INC Absolute",
    0xEF: "Undefined",
    0xF0: "BEQ",
    0xF1: "SBC (Indirect),Y",
    0xF2: "Undefined",
    0xF3: "Undefined",
    0xF4: "Undefined",
    0xF5: "SBC Zero Page,X",
    0xF6: "INC Zero Page,X",
    0xF7: "Undefined",
    0xF8: "SED",
    0xF9: "SBC Absolute,Y",
    0xFA: "Undefined",
    0xFB: "Undefined",
    0xFC: "Undefined",
    0xFD: "SBC Absolute,X",
    0xFE: "INC Absolute,X",
    0xFF: "DEDUG_HALT",
}